"""modificar tabla pedidos

Revision ID: 0f12dbdd3ebd
Revises: b8eaaf2174b6
Create Date: 2026-07-21 17:44:20.216488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f12dbdd3ebd'
down_revision: Union[str, Sequence[str], None] = 'b8eaaf2174b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
