"""Agregar campo stock a producto

Revision ID: 6258a4fb1f26
Revises: 79afd6b08f75
Create Date: 2026-07-21 18:44:23.059681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6258a4fb1f26'
down_revision: Union[str, Sequence[str], None] = '79afd6b08f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
