"""agregar tablas de carrito y pedidos

Revision ID: 7085518e366e
Revises: 6da16bfcbccf
Create Date: 2026-07-20 18:29:04.341997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7085518e366e'
down_revision: Union[str, Sequence[str], None] = '6da16bfcbccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
