"""modificar tabla pedidos

Revision ID: b8eaaf2174b6
Revises: 688382632f9b
Create Date: 2026-07-21 17:42:03.613110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8eaaf2174b6'
down_revision: Union[str, Sequence[str], None] = '688382632f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pedidos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'usuario_id')
    # ### end Alembic commands ###
