"""Agregar relación carrito a usuario

Revision ID: bd5d598aa888
Revises: 0f12dbdd3ebd
Create Date: 2026-07-21 17:57:00.184893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5d598aa888'
down_revision: Union[str, Sequence[str], None] = '0f12dbdd3ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
